theme: jekyll-theme-minimal
title: ADA Template Website
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: Test plots
    url: /results/Step 2-2.html
